version: "3.8"
services:
  mongodb:
    image: mongodb
    build:
      context: ./mongodb
  api:
    image: rss_trendy_api
    build:
        context: ./api
        dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: rss_trendy_client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"