version: "3.8"
services:
  mongodb:
    image: mongo
    build:
      context: ./mongodb
  nginx:
    image: ngnix
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: rss_trendy_api
    build:
        context: ./api
        dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: rss_trendy_client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
